source 'https://rubygems.org'

gem 'rake'
gem 'opal'
gem 'opal-browser'
gem 'rails'
gem 'opal-rails', '>= 0.8.1'
gem 'react-rails', '~> 1.9.0'
gem 'hyper-operation'
gem 'hyperloop-config'
gem 'opal-jquery'
